# Custom Settings for our application
clothes-marketplace:
  env: ${DeploymentEnv}
  thread-pool-size: 20
  authorization-required-uris:
    - /publisher
  authorization-allowed-uris:
    - /authenticate
    - /marketplace/**
    - /health
    - /swagger-ui/**
    - /v3/api-docs/**
springdoc:
  packagesTo-scan: 
    - com.ravid.clothes_marketplace.server
    - com.ravid.clothes_marketplace.server.api
    - com.ravid.clothes_marketplace.app.service
  paths-to-match: /**
  swagger-ui:
    use-root-path: true

server:
  http2:
    enabled: true
  port: 2000
  # additional-ports: 2004
  ssl:
    # client-auth: need
    enabled: false
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

logging:
  # config: classpath:logback-spring.xml
  app-log-root: ${LOG_ROOT:-log}
  log-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ---[%5.15t] %-20.40c{1} : %msg%n%ex"
  appender-type: ${LOGGER_APPENDER:-Text}
jwt:
  secret: "c3VwZXItc2VjcmV0LXN0cmluZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dn"
# Database Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DbUrl}${DbName}${DbParams}
    username: ${DBusername}
    password: ${DBpassword}
    hikari:
      max-lifetime: 300000 
  jpa:
    database: mysql
    defer-datasource-initialization: true
    properties:
      hibernate:
        "[enable_lazy_load_no_trans]": true
  sql:
    init:
      mode: always
    # continue-on-error: true