# This is a basic workflow that is manually triggered

name: Build and push

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  release:
    types: [created, edited]

jobs:
  build-and-push:
    if: github.event.release.draft == false && github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set VERSION environment variable
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Restore buildx cache
        id: cache-buildx-restore
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-clothes_marketplace_buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-clothes_marketplace_buildx-

      # - name: Restore maven cache
      #   id: cache-maven-restore
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: ~/.m2/repository
      #     key: ${{ runner.os }}-DWM_maven-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-DWM_maven-
      
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache,mode=max
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          push: true
          tags: |
            ${{ vars.IMAGE_NAME }}:latest
            ${{ vars.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ vars.IMAGE_NAME }}:${{ github.sha }}
      
      - name: echo ls cache
        working-directory : "/tmp/.buildx-cache"
        run: "ls -laR"
      #   run: |
      #     curl -X POST \
      #         -H "Content-Type: application/json" \
      #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #         -d '{"event_type": "dwm_master_tag", "client_payload": {"image_name": "clothes_marketplace:${{ env.VERSION }}", "key2": "value2"}}' \
      #       https://jenkins.example.com/github-webhook/
