# This is a basic workflow that is manually triggered

name: Tag flow

on:
  push:
    branches:
      - changes

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Get version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Set VERSION environment variable
      run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      
    - name: echo version
      run: echo ${{ env.VERSION }}
    
    - name: echo sha
      run: echo ${{ github.sha }}

    - name: echo refver
      run: echo ${{ steps.version.outputs.version }}
